# this workflow runs only for the build after each commit for macOS

name: Build Bank App (macOS, Apple Silicon)
on:
  push:
    branches: ["*"] #pushed from all branches
  pull_request:
    branches: ["main"]     
jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [clang_64]  # supports both Intel and Apple Silicon
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.1'
          host: 'mac'
          target: 'desktop'
          arch: ${{ matrix.arch }}
          cache: true
      
      - name: Configure CMake
        shell: bash
        run: |
          cmake -S bank-automat -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_PREFIX_PATH="${Qt6_DIR}"
      
      - name: Build
        shell: bash
        run: |
          cmake --build build --config Release
      
      - name: Package app for CI
        shell: bash
        run: |
          cp -r build/Release/Pankkiautomaatti.app build/Release/BankApp-arm64.app
      
      - name: Upload artifact (for CI)
        uses: actions/upload-artifact@v4
        with:
          name: BankApp-macOS-arm64
          path: build/Release/BankApp-arm64.app